site_name: Pastglory Docs
nav:
  - Home: index.md
  - Digital Design and Verification:
    - From SPEC to RTL: digital/spec2rtl.md
    - Common Cells: digital/common_cells.md
    - FIFO: digital/fifo.md
  - Deep Learning:
    - PyTorch Notes: dl/torch.md
  - Tools:
    - Verilog on MacOS: tools/verilog_on_mac.md

  - About: 
    - Pastglory: about/pastglory.md
theme: readthedocs