site_name: Pastglory Docs
nav:
  - 主页: index.md
  - 数字设计与验证:
    - 通用模块: digital/common_cells.md
  - 程序设计与算法:
    - Python笔记: pa/python.md
    - PyTorch笔记: pa/torch.md
  - 工具:
    - Verilog on macOS: tools/verilog_on_mac.md
    - Git: tools/git_command.md
    - GitBook: tools/gitbook.md
  - 杂谈:
    - 如何正确提问: talk/ask_question.md 
  - 关于: 
    - Pastglory: about/pastglory.md
theme: readthedocs
markdown_extensions:
  - admonition
  - pymdownx.superfences